version: "3.8"

networks:
  ai-network:
    driver: bridge

services:
  db:
    image: postgres:15-alpine
    container_name: ai-db
    networks:
      - ai-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ai_learning_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ai_learning_dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ai-service:
  #   build: ./ai-service
  #   container_name: ai-fastapi
  #   networks:
  #     - ai-network
  #   volumes:
  #     - ./ai-service/storage:/app/storage
  #     - ./uploads:/app/uploads
  #   restart: unless-stopped

  backend:
    build: ./backend
    container_name: ai-backend
    networks:
      - ai-network
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ai_learning_dashboard
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      AI_SERVICE_URL: http://host.docker.internal:8000
      APP_DIR_UPLOADS: /app/uploads
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://localhost:8080/api/v1"
    container_name: ai-frontend
    networks:
      - ai-network
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_flyspeech
    networks:
      - ai-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  prometheus:
    image: prom/prometheus:latest
    container_name: ai-learning-dashboard-prometheus
    networks:
      - ai-network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: ai-learning-dashboard-grafana
    networks:
      - ai-network
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  redis_data:
  grafana-storage: