export const COURSES = [
  {
    id: 1,
    title: "Toán rời rạc – Khóa học đầy đủ",
    lessons: 12,
    progress: 75,
    status: "in-progress",
    color: "blue",
    bg: "#EEF1FE",
    icon: "🔢",
  },
  {
    id: 2,
    title: "Nguyên tắc cơ bản của AI",
    lessons: 5,
    progress: 75,
    status: "in-progress",
    color: "blue",
    bg: "rgb(240, 250, 255)",
    icon: "🤖",
  },
  {
    id: 3,
    title: "Toán rời rạc – Kiến thức cơ bản",
    lessons: 10,
    progress: 60,
    status: "in-progress",
    color: "blue",
    bg: "#EDFAF6",
    icon: "📐",
  },
  {
    id: 4,
    title: "Kiến thức cơ bản và nâng cao về Trí tuệ nhân tạo",
    lessons: 11,
    progress: 100,
    status: "completed",
    color: "blue",
    bg: "#FFF0F5",
    icon: "🧠",
    badge: "done",
  },
  {
    id: 5,
    title: "Phân tích chuyên sâu về lý thuyết đồ thị",
    lessons: 8,
    progress: 30,
    status: "completed",
    color: "blue",
    bg: "#EEF1FE",
    icon: "🕸",
  },
  {
    id: 6,
    title: "Xác suất và Thống kê",
    lessons: 12,
    progress: 100,
    status: "completed",
    color: "blue",
    bg: "#fff7eea5",
    icon: "📊",
    badge: "done",
  },
];

export const TABS = [
  { key: "all", labelKey: "my_courses.tabs.all" },
  { key: "in-progress", labelKey: "my_courses.tabs.in_progress" },
  { key: "completed", labelKey: "my_courses.tabs.completed" },
];
