export const COURSES = [
  {
    id: 1,
    title: "Discrete Math – Complete Course",
    lessons: 12,
    progress: 75,
    status: "in-progress",
    color: "blue",
    bg: "#EEF1FE",
    icon: "🔢",
  },
  {
    id: 2,
    title: "AI Fundamental",
    lessons: 5,
    progress: 75,
    status: "in-progress",
    color: "blue",
    bg: "rgb(240, 250, 255)",
    icon: "🤖",
  },
  {
    id: 3,
    title: "Discrete Math – Fundamental",
    lessons: 10,
    progress: 60,
    status: "in-progress",
    color: "blue",
    bg: "#EDFAF6",
    icon: "📐",
  },
  {
    id: 4,
    title: "AI Fundamental Advanced",
    lessons: 11,
    progress: 100,
    status: "completed",
    color: "blue",
    bg: "#FFF0F5",
    icon: "🧠",
    badge: "Done",
  },
  {
    id: 5,
    title: "Graph Theory Deep Dive",
    lessons: 8,
    progress: 30,
    status: "completed",
    color: "blue",
    bg: "#EEF1FE",
    icon: "🕸",
  },
  {
    id: 6,
    title: "Probability & Statistics",
    lessons: 12,
    progress: 100,
    status: "completed",
    color: "blue",
    bg: "#fff7eea5",
    icon: "📊",
    badge: "Done",
  },
];

export const TABS = [
  { key: "all", label: "All" },
  { key: "in-progress", label: "In Progress" },
  { key: "completed", label: "Completed" },
];
