spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_learning_dashboard
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true