spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_learning_dashboard
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 652291090161-jl10a5ld9ugehmf20rp6asq5mhtbpgj9.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

jwt:
  signerKey: "3af58fafc186e3e97a499c70732004cbac3e58ca779189091e038c8a80a179ae"

ai:
  service:
    url: "http://localhost:8000"

app:
  dir:
    uploads: "uploads"