spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_learning_dashboard
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 652291090161-jl10a5ld9ugehmf20rp6asq5mhtbpgj9.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

jwt:
  signerKey: "3af58fafc186e3e97a499c70732004cbac3e58ca779189091e038c8a80a179ae"

ai:
  service:
    url: "http://localhost:8000"

app:
  dir:
    uploads: "uploads"
vnpay:
  tmn-code: 858C6TFV
  secret-key: EFHOGXXC4RQCLPQIRIXSVEJEKFPIS46E
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: http://localhost:5173/app/premium
momo:
  partner-code: MOMO5RGW20191128
  access-key: mS6n6S3u4S3u4S3u
  secret-key: F8BBA842ECF85D152590E8D1D1650D67
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  return-url: http://localhost:3000/payment/success
  notify-url: http://localhost:8080/api/payment/momo-ipn